project: pa
pinecone_index: pa
embedding_model: openai-3-large     # was openai-3-small
dimension: 3072                      # match the existing index!
env_file: .env.pa
chunk_size: 400
chunk_overlap: 50
input_streams:
  - type: notes
    path: ./test_data/pa/
    content_types: [txt, md]
metadata:
  project: "PA"
  assistant: "pa"
